Accounting/Models/ViewModel/AccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Accounting.Models.ViewModel
{
	public class AccountViewModel
	{
		public enum E_Accou_Type { Income, OutCome };
		public E_Accou_Type Type { get; set; }
		public int Amount {get; set;}
		public DateTime Date { get; set; }
		public string Comment { get; set; }
	}
}

Accounting/Controllers/AccountingController.cs
using Accounting.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Accounting.Controllers
{
    public class AccountingController : Controller
    {
        // GET: Accounting
        public ActionResult AccountIndex()
        {
			List<AccountViewModel> pageData = new List<AccountViewModel>();

			for(int i = 1; i < 5; i++)
			{
				if(i == 3)
				{
					pageData.Add(
					new AccountViewModel()
					{ Amount = i * 30, Date = DateTime.Now, Type = AccountViewModel.E_Accou_Type.Income, Comment = "" }
					);
				}
				else
				{
					pageData.Add(
					new AccountViewModel()
					{ Amount = i * 30, Date = DateTime.Now, Type = AccountViewModel.E_Accou_Type.OutCome, Comment = "" }
					);
				}				
			}

			return View(pageData);
        }
    }
}

Accounting/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Accounting.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

Accounting/Views/Accounting/AccountIndex.cshtml
@{ 
	ViewBag.Title = "記帳本";
}


    
    <div class="container body-content">
		<div class="well">
			<form class="form-horizontal">
				<div class="form-group">
					<label for="category" class="col-sm-2 control-label">類別</label>
					<div class="col-sm-10">
						<select id="category" class="form-control">
							<option value="" selected>請選擇</option>
							<option>支出</option>
							<option>收入</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label for="money" class="col-sm-2 control-label">金額</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="money" placeholder="金額">
					</div>
				</div>
				<div class="form-group">
					<label for="date" class="col-sm-2 control-label">日期</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="date" placeholder="日期">
					</div>
				</div>
				<div class="form-group">
					<label for="description" class="col-sm-2 control-label">備註</label>
					<div class="col-sm-10">
						<textarea class="form-control" id="description">
						</textarea>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-8 col-sm-4">
						<button type="submit" class="btn btn-default">送出</button>
					</div>
				</div>
			</form>
		</div>

	@Html.Partial("_historyData")

    
    </div>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.1.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"></script>

Accounting/Views/Accounting/_historyData.cshtml
@model ICollection<Accounting.Models.ViewModel.AccountViewModel>

<div class="row">
	<div class="col-md-12">
		<table class="table table-bordered table-hover">
			<tr>
				<th>#</th>
				<th>日期</th>
				<th>類別</th>
				<th>金額</th>
				<th>備註</th>
			</tr>			
			
			@{
				int count = 0;
				foreach (var item in Model)
				{
					count++;
					<tr>
						<td> @count </td>
						<td> @item.Date</td>
						@{
							if (item.Type == Accounting.Models.ViewModel.AccountViewModel.E_Accou_Type.Income)
							{
								<td>收入</td>
							}
							else
							{
								<td>支出</td>
							}
						}
						<td>@item.Amount</td>

						<td>@item.Comment</td>
					</tr>
				}
			}
			

		</table>
	</div>
</div>

Accounting/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Accounting/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Accounting/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Accounting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
					<li>@Html.ActionLink("記帳本", "AccountIndex", "Accounting")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
		<footer>
			<p>&copy; 2017 - <a href="#">SkillTree</a></p>
		</footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>